### ISSUE TITLE
Newline characters are removed from output

### ISSUE THREAD

**Issue by brodziakm** [matt-allan/envtpl#1]
Firstly, thanks for an excellent little utility - this is perfect for our build pipeline.

I have encountered an apparent bug (that may well be due to my lack of expertise in Bash, so apologies if I am doing something wrong). If I have a source file (say source.txt):

```
line1
line2
line3
```

And I issue this command:

```echo "$(< source.txt)" | ./envtpl```

I expect:

```
line1
line2
line3
````

but get:

```line1 line2 line3```

**Comment by matt-allan** [comment]
Hey,

I think the command substitution (the `$()` part) is trimming the newlines. 

https://wiki.bash-hackers.org/syntax/expansion/cmdsubst

if you reduce it to this it should work:


```
< source.txt | ./envtpl
``` 

 Or more idiomatically:

```
./envtpl < source.txt
``` 

https://wiki.bash-hackers.org/howto/redirection_tutorial?s%5B%5D=redirection#input_redirection_n_file

I will add better examples to the README.

**Comment by matt-allan** [comment]
Well actually it looks like I broke newlines too, so in addition to the above I will need to push a fix for that 😬

**Comment by matt-allan** [comment]
This should be fixed now. I just tagged `0.3.0` with the fix. Thanks for reporting this and letting me know someone's using it already!

**Comment by brodziakm** [comment]
Cheers Matt, that's awesome :)
